### ISSUE TITLE
Change z-index for #jquery-overlay and #jquery-lightbox

### ISSUE THREAD

**Issue by lck-git** [davidstutz/cmsimple-pictures#1]
In einigen Templates gibt es Probleme mit der Anzeige in der Lightbox, da die Templates z.b. für das Menü einen höheren z-index gesetzt haben als #jquery-overlay and #jquery-lightbox.
Siehe deine [Demo-Seite](http://davidstutz.de/cmsimplexhdemo/?Pictures), wenn die Seite ganz nach oben gescrollt ist.

![picture_issue_z-index](https://user-images.githubusercontent.com/22255655/34649091-05d0725a-f3a8-11e7-91c8-f2d4040ea882.jpg)

**Comment by davidstutz** [comment]
Danke für den Hinweis. Das ist zwar Template-spezifisch, aber für die Demo habe ich es trotzdem schnell gefixt.
